### PR TITLE
[Pre Commit] Added hook to warn about .lock files

### PR DESCRIPTION
**Pull request by harooks**
## Describe your changes
I added a hook to the pre-commit to not let you add .lock files.

## JIRA Ticket Link
NA

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [x] Is the code correctly formatted?
- [ ] If this is a feature, is there a related Notion document for the feature?

### CODE REVIEW

**Review by mingilee98 — COMMENTED** [review]
I thought generally .lock files should be added to the commit for managing dependencies. Is there a reason that we want to not add .lock files?

https://stackoverflow.com/questions/48524417/should-the-package-lock-json-file-be-added-to-gitignore

**Comment by harooks** [comment]
> I thought generally .lock files should be added to the commit for managing dependencies. Is there a reason that we want to not add .lock files?
> 
> https://stackoverflow.com/questions/48524417/should-the-package-lock-json-file-be-added-to-gitignore

Oh really? I thought we didn't need them and because it makes a new one every time we yarn install. And it causes merge conflicts when you add them to the commit. But ignore this if we need it!

**Comment by dtlaurianti** [comment]
It will regenerate yarn.lock when you yarn install, but yarn.lock stores the actual versions of the deps we have installed, we want to keep it to maintain consistent installs and not have to deal with dep conflicts over and over again

**Comment by harooks** [comment]
> It will regenerate yarn.lock when you yarn install, but yarn.lock stores the actual versions of the deps we have installed, we want to keep it to maintain consistent installs and not have to deal with dep conflicts over and over again

ohh i see, then ill start adding yarn.lock files to my commits

**Pull request closed without merging**
