### PR TITLE
Mobile local database

### PR DESCRIPTION
**Pull request by harooks**
## Describe your changes
Created local database for mobile.
Right now it automatically saves the events to local, and then to remote if they have access, so there's no difference in the behavior. But later I can change it sync to remote db every hour or so. 

## JIRA Ticket Link
https://septeam4.atlassian.net/browse/T4-75

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] If it is a core feature, I have added thorough tests.
- [x] Is the code correctly formatted?
- [ ] If this is a feature, is there a related Notion document for the feature?

### CODE REVIEW

**Review by SergioMEV — COMMENTED** [review]
lgtm.

**Review by SergioMEV — APPROVED** [review]

**Review by dtlaurianti — COMMENTED** [review]
image
Is there a reason why we want this globally disabled?  This seems like something I would like enforced.

**Review by dtlaurianti — APPROVED** [review]
Overall looks great! One minor issue I see is I believe the way you are creating the ids has a tiny tiny chance to cause collisions, if there is a way you can just have the sqlite make the ids that might be better.  LGTM

**Comment by dtlaurianti** [comment]
Rebase to remove merge-style history

**Pull request merged**
