### PR TITLE
[feat] Medicine tracking

### PR DESCRIPTION
**Pull request by SergioMEV**
## Describe your changes
Adds medicine tracking screen to mobile. Adds medicine routes to backend for keeping track of medicine types for each user. Fixes previously failing tests in mobile. You need to run "yarn expo prebuild --clean; yarn run ios" to run the mobile simulator for ios. 

## JIRA Ticket Link
https://septeam4.atlassian.net/browse/T4-24?atlOrigin=eyJpIjoiYmE4ZTM1OTZjYzNiNGMxY2I0ODg3YWQyNzNmMmJjZDgiLCJwIjoiaiJ9

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] If it is a core feature, I have added thorough tests.
- [x] Is the code correctly formatted?
- [ ] If this is a feature, is there a related Notion document for the feature?

### CODE REVIEW

**Review by dtlaurianti — CHANGES_REQUESTED** [review]
Rejecting because of heavy schema & API changes without any testing.  Also would appreciate screenshots of the new views.

**Comment by SergioMEV** [comment]
:( ok. I’ll do the tests for the backend :(((( I didn’t put screenshots
because you saw it in the presentation.

**Comment by SergioMEV** [comment]
Added the tests and fixed all the previous tests that had broken because of schema changes!

**Review by harooks — APPROVED** [review]
yeyy for testing

**Review by mingilee98 — APPROVED** [review]
LGTM!

**Review by dtlaurianti — APPROVED** [review]

**Pull request merged**
