### PR TITLE
SleepTimer backend integrate

### PR DESCRIPTION
**Pull request by harooks**
## Describe your changes
- connect sleep timer to database
- Added button to indicate crib time

## JIRA Ticket Link
https://septeam4.atlassian.net/browse/T4-82

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] If it is a core feature, I have added thorough tests.
- [x] Is the code correctly formatted?
- [ ] If this is a feature, is there a related Notion document for the feature?

### CODE REVIEW

**Comment by SergioMEV** [comment]
Can you change the background color of all the screens to white? Camila said she wanted that so that she could figure out the design. It should only be a few that don't have it.

**Comment by harooks** [comment]
> Can you change the background color of all the screens to white? Camila said she wanted that so that she could figure out the design. It should only be a few that don't have it.

ok done

**Review by mingilee98 — APPROVED** [review]
LGTM!

**Review by SergioMEV — APPROVED** [review]
lgtm!

**Pull request merged**
