### PR TITLE
[feat] Sleep timer 

### PR DESCRIPTION
**Pull request by harooks**
## Describe your changes
- Created the sleep timer view that contains:
  - start time that logs time start was pressed
  - stop time that logs time stop was pressed
  - elapsed time that counts the elapsed time in seconds
  - start/stop button

- I also had a issue with eslint with the navigation package so I added some lines in `.eslintrc.yml`

## JIRA Ticket Link
https://septeam4.atlassian.net/browse/T4-7

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] If it is a core feature, I have added thorough tests.
- [x] Is the code correctly formatted?
- [ ] If this is a feature, is there a related Notion document for the feature?

## Screenshot
I will make it prettier

### CODE REVIEW

**Review by mingilee98 — APPROVED** [review]

**Review by SergioMEV — APPROVED** [review]
lgtm!

**Comment by dtlaurianti** [comment]
Please modify .eslintrc for the mobile folder which overrides the rules you need, unless you think those rules should be overridden globally.  I made a commit that does this.

**Review by dtlaurianti — APPROVED** [review]

**Comment by harooks** [comment]
@dtlaurianti  

Could you fix the formal check workflow so I can rebase it?

**Comment by dtlaurianti** [comment]
Pretty sure my workflow works, just PRs that got added before it didn't trigger it.  I think if you approve and merge my PR for the workflow we should be able to manually trigger it.

**Pull request merged**
