### PR TITLE
Mobile skeleton

### PR DESCRIPTION
**Pull request by harooks**
## Describe your changes
Set up skeleton for mobile app. 

## How to set up
0. Download the expo app on your phone
1. run it with the command `npx expo start`
2. There should be a QR code that you can scan to simulate
3. You can also choose xcode or android studio simulator to simulate

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [x] Is the code correctly formatted?
- [ ] If this is a feature, is there a related Notion document for the feature?

### CODE REVIEW

**Review by dtlaurianti — COMMENTED** [review]
You have used yarn for package management which may actually be the better option, but I have used npm workspaces for the monorepo setup we currently have.  It could be worth switching the project over to yarn but idk the pros and cons

**Comment by dtlaurianti** [comment]
Expo primarily supports yarn classic, which appears to be somewhat outdated at this point (yarn 2 came out in 2020).  I think we can make it work with any, but should probably go with what expo supports because expo specifically has its own package requirements for the versions that is can "translate" into native code, which it manages automatically if we use yarn classic.  I think me and Sergio should work together to get the repo switched over to yarn and create a dev env dockerimage for everyone to use.

**Comment by SergioMEV** [comment]
> Expo primarily supports yarn classic, which appears to be somewhat outdated at this point (yarn 2 came out in 2020). I think we can make it work with any, but should probably go with what expo supports because expo specifically has its own package requirements for the versions that is can "translate" into native code, which it manages automatically if we use yarn classic. I think me and Sergio should work together to get the repo switched over to yarn and create a dev env dockerimage for everyone to use.

I'm down, but can this wait until next sprint? I want to finish the API stuff before moving on. I'll look more into Docker in the meanwhile.

**Comment by harooks** [comment]
Imma redo this using another template so don't merge

**Pull request closed without merging**
