### PR TITLE
Sleep plan backend integrate

### PR DESCRIPTION
**Pull request by mingilee98**
## Describe your changes
Integrated the sleep plan uploading UI with the backend

https://github.com/uiowaSEP2024/004_SleepTrak/assets/60719119/fbce0e4a-2277-4a4b-a03a-dc2688e7c47a

## JIRA Ticket Link
https://septeam4.atlassian.net/browse/T4-77?atlOrigin=eyJpIjoiN2NmYzRmODI3OTQ4NGQzZmJhZDMzYmMzZDg0YjgwOWUiLCJwIjoiaiJ9

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] If it is a core feature, I have added thorough tests.
- [x] Is the code correctly formatted?
- [ ] If this is a feature, is there a related Notion document for the feature?

### CODE REVIEW

**Comment by mingilee98** [comment]
I could not add sad path / error path for recommendedPlans due to a problem in mocking **get: jest.spyOn(prisma.baby, 'findUnique')** Would appreciate help on this

**Review by SergioMEV — APPROVED** [review]
lgtm! I think some of your commits could be squashed into a single commit, but its good anyways. Better too small than too big.

**Review by dtlaurianti — COMMENTED** [review]
Leaving the rest of the testing to Mingi since he knows what all he added.  Hopefully should be smooth with the examples and changes I added

**Comment by SergioMEV** [comment]
Is this ready?

**Comment by mingilee98** [comment]
> Is this ready?

yes!

**Review by harooks — APPROVED** [review]

**Pull request merged**
