### PR TITLE
<Mobile> Adding UI library and Test Configuration

### PR DESCRIPTION
**Pull request by harooks**
## Describe your changes
- Added the main navigation tab for the app 
- Installed UI library [React Native Paper](https://reactnativepaper.com/)
- Jest configuration 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] If it is a core feature, I have added thorough tests.
- [x] Is the code correctly formatted?
- [ ] If this is a feature, is there a related Notion document for the feature?

### CODE REVIEW

**Review by SergioMEV — APPROVED** [review]
lgtm!

**Comment by dtlaurianti** [comment]
Getting some warning on Yarn install after your package.json changes, lets resolve those before merging

**Comment by harooks** [comment]
> Getting some warning on Yarn install after your package.json changes, lets resolve those before merging

Can you send me warning your getting? @harooks

**Review by dtlaurianti — APPROVED** [review]
Looks great, I added a commit because the package.json had react/react-native in both deps and devDeps, which is redundant

**Pull request merged**
