### PR TITLE
[feat] Web auth flow

### PR DESCRIPTION
**Pull request by SergioMEV**
## Describe your changes
Added web authentication using auth0. Protected all the routes on the web app. Set up API token authentication for the web app, meaning the web app and the backend can now talk to each other. There are examples of how to do this in your components in the components/auth.tsx file. I have modified some of the current tests to test the basic auth components, but more extensive tests are required to test that the auth0 functions are being called correctly. I tried for hours to get that to work and failed. I will try again next sprint, since I do not believe testing the auth0 stuff is super high priority.

### Important
You need the auth .env variables for this to work. I will send them over email to you guys tomorrow.

## JIRA Ticket Link
https://septeam4.atlassian.net/browse/T4-12?atlOrigin=eyJpIjoiNGMzMzU1ZTkxZjljNGE4NjkyZTc0MTEzZDc1YjJhOGUiLCJwIjoiaiJ9

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [x] Is the code correctly formatted?
- [ ] If this is a feature, is there a related Notion document for the feature?

### CODE REVIEW

**Review by mingilee98 — APPROVED** [review]
I think the createBrowserRouter is more recent / is what React Router recommends.

https://reactrouter.com/en/main/routers/create-browser-router
https://stackoverflow.com/questions/77887184/react-router-createbrowserrouter-vs-browser-router

I don't think it will make a big difference, so I will approve it. We can change it later if we have time. Or you can push it to this commit if you have time.

**Comment by dtlaurianti** [comment]
Why did you change the web server to run on port 3000?  This is the same port the backend uses and will cause issues.  Also the port numbers are redefined in many places maybe we should make a central config file to set the ports.

**Comment by SergioMEV** [comment]
> Why did you change the web server to run on port 3000? This is the same port the backend uses and will cause issues. Also the port numbers are redefined in many places maybe we should make a central config file to set the ports.

How will that cause issues? They are going to be running on different servers.

**Comment by SergioMEV** [comment]
I changed it because that is convention for the auth0 callbacks. I can change it back, but I don't see how it would be an issue in prod.

**Comment by dtlaurianti** [comment]
Yeah not an issue in prod but its both localhost:3000 for us developers.  We can change the backend port to comply with the conventions

**Comment by SergioMEV** [comment]
> Yeah not an issue in prod but its both localhost:3000 for us developers. We can change the backend port to comply with the conventions

I changed this one. Let's leave the backend as 3000.

**Review by dtlaurianti — APPROVED** [review]
I trust in the goat

**Pull request merged**
